name: Build V-Downloader APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Signing Secrets
        run: |
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "::error::Signing secrets are missing. Cannot build release APK."
            exit 1
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" > keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "storeFile=../keystore.jks" >> keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties

      - name: Build APK
        run: chmod +x ./gradlew && ./gradlew --no-daemon clean assembleGenericRelease

      - name: Setup Build Tools
        run: |
          BUILD_TOOLS_VERSION=$(ls $ANDROID_HOME/build-tools | sort -n | tail -1)
          echo "BUILD_TOOLS_PATH=$ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION" >> $GITHUB_ENV

      - name: Zipalign and Sign APKs
        run: |
          mkdir -p signed_apks
          for APK_PATH in $(find app/build/outputs/apk/generic/release/ -name "*.apk"); do
            APK_NAME=$(basename $APK_PATH)
            ALIGNED_APK="aligned_$APK_NAME"
            SIGNED_APK="signed_apks/$APK_NAME"
            $BUILD_TOOLS_PATH/zipalign -v -p 4 "$APK_PATH" "$ALIGNED_APK"
            $BUILD_TOOLS_PATH/apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.STORE_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --out "$SIGNED_APK" "$ALIGNED_APK"
          done

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: V-Downloader-Release
          path: signed_apks/*.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: signed_apks/*.apk
          draft: false
          prerelease: false
